/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit;

import de.validas.spedit.AbstractNaturalLangRuntimeModule;
import de.validas.spedit.converters.NaturalLangValueConverters;
import de.validas.spedit.naming.NlxDeclarativeQualifiedNameProvider;
import javax.annotation.Generated;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.naming.IQualifiedNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangRuntimeModule extends AbstractNaturalLangRuntimeModule {
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return NlxDeclarativeQualifiedNameProvider.class;
  }
  
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return NaturalLangValueConverters.class;
  }
}
