/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.nlx.naturalLang.Array#getName <em>Name</em>}</li>
 *   <li>{@link org.xixum.nlx.naturalLang.Array#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getArray()
 * @model
 * @generated
 */
public interface Array extends NoNElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference list.
   * The list contents are of type {@link org.xixum.nlx.naturalLang.NoNElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference list.
   * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getArray_Name()
   * @model containment="true"
   * @generated
   */
  EList<NoNElement> getName();

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.xixum.nlx.naturalLang.BracketSentence}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parameters</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getArray_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<BracketSentence> getParameters();

} // Array
