/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Brackets</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getBrackets()
 * @model
 * @generated
 */
public interface Brackets extends NoNElement
{
} // Brackets
