/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter Alpha</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getChapterAlpha()
 * @model
 * @generated
 */
public interface ChapterAlpha extends NoNElementX2
{
} // ChapterAlpha
