/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Elements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.nlx.naturalLang.Elements#getNl <em>Nl</em>}</li>
 * </ul>
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getElements()
 * @model
 * @generated
 */
public interface Elements extends AllElements, New_Line
{
  /**
   * Returns the value of the '<em><b>Nl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nl</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nl</em>' attribute.
   * @see #setNl(String)
   * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getElements_Nl()
   * @model
   * @generated
   */
  String getNl();

  /**
   * Sets the value of the '{@link org.xixum.nlx.naturalLang.Elements#getNl <em>Nl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nl</em>' attribute.
   * @see #getNl()
   * @generated
   */
  void setNl(String value);

} // Elements
