/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ext Bracket Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getExtBracketSentence()
 * @model
 * @generated
 */
public interface ExtBracketSentence extends BracketSentence
{
} // ExtBracketSentence
