/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>It Word</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.nlx.naturalLang.ItWord#getWord <em>Word</em>}</li>
 * </ul>
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getItWord()
 * @model
 * @generated
 */
public interface ItWord extends NoNElement
{
  /**
   * Returns the value of the '<em><b>Word</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Word</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Word</em>' attribute list.
   * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getItWord_Word()
   * @model unique="false"
   * @generated
   */
  EList<String> getWord();

} // ItWord
