/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>No NElement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getNoNElement()
 * @model
 * @generated
 */
public interface NoNElement extends NoNElementX, NoNElementX2
{
} // NoNElement
