/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quote</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.nlx.naturalLang.Quote#getQuote <em>Quote</em>}</li>
 * </ul>
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getQuote()
 * @model
 * @generated
 */
public interface Quote extends NoNElement
{
  /**
   * Returns the value of the '<em><b>Quote</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Quote</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quote</em>' attribute.
   * @see #setQuote(String)
   * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getQuote_Quote()
   * @model
   * @generated
   */
  String getQuote();

  /**
   * Sets the value of the '{@link org.xixum.nlx.naturalLang.Quote#getQuote <em>Quote</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quote</em>' attribute.
   * @see #getQuote()
   * @generated
   */
  void setQuote(String value);

} // Quote
