/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sentence X</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getSentenceX()
 * @model
 * @generated
 */
public interface SentenceX extends EObject
{
} // SentenceX
