/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Symbols X</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getSymbolsX()
 * @model
 * @generated
 */
public interface SymbolsX extends NoNElement
{
} // SymbolsX
