/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Word Short</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.nlx.naturalLang.NaturalLangPackage#getWordShort()
 * @model
 * @generated
 */
public interface WordShort extends NoNElementX, Elements
{
} // WordShort
