/*
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.ui.tests;

import com.google.inject.Injector;

import org.eclipse.xtext.testing.IInjectorProvider;
import org.xixum.nlx.model.model.ui.internal.IeditActivator;

public class NaturalLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IeditActivator.getInstance().getInjector("org.xixum.nlx.naturalLang");
	}

}
