/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit;

import de.validas.spedit.NaturalLangStandaloneSetupGenerated;
import javax.annotation.Generated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangStandaloneSetup extends NaturalLangStandaloneSetupGenerated {
  public static void doSetup() {
    new NaturalLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
