/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.tests;

import de.validas.spedit.naturalLang.Model;
import de.validas.spedit.tests.NaturalLangInjectorProvider;
import javax.annotation.Generated;

/* @ExtendWith(/* name is null */)
@InjectWith(NaturalLangInjectorProvider.class) */@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangParsingTest {
  /* @Inject
   */private /* ParseHelper<Model> */Object parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nThe field NaturalLangParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\nassertNotNull cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nassertTrue cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
