/*
 * generated by Xtext 2.16.0
 */
package org.xixum.nlxweb;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link NaturalLangWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractNaturalLangWebModule extends DefaultWebModule {

}
