/*
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NaturalLangStandaloneSetup extends NaturalLangStandaloneSetupGenerated {

	def static void doSetup() {
		new NaturalLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
