/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.ui.outline;

import javax.annotation.Generated;
import org.eclipse.jface.text.source.ISourceViewer;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangOutlineTreeProvider extends DefaultOutlineTreeProvider {
  protected ISourceViewer textViewer;
}
