/*
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.parser.antlr;

import com.google.inject.Inject;
import org.xixum.nlx.parser.antlr.internal.InternalNaturalLangParser;
import org.xixum.nlx.services.NaturalLangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class NaturalLangParser extends AbstractAntlrParser {

	@Inject
	private NaturalLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_SPACE");
	}
	

	@Override
	protected InternalNaturalLangParser createParser(XtextTokenStream stream) {
		return new InternalNaturalLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public NaturalLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(NaturalLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
