/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.validas.spedit.NaturalLangRuntimeModule;
import de.validas.spedit.NaturalLangStandaloneSetup;
import de.validas.spedit.ide.NaturalLangIdeModule;
import javax.annotation.Generated;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangIdeSetup extends NaturalLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    NaturalLangRuntimeModule _naturalLangRuntimeModule = new NaturalLangRuntimeModule();
    NaturalLangIdeModule _naturalLangIdeModule = new NaturalLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_naturalLangRuntimeModule, _naturalLangIdeModule));
  }
}
