/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.ide;

import de.validas.spedit.ide.AbstractNaturalLangIdeModule;
import javax.annotation.Generated;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangIdeModule extends AbstractNaturalLangIdeModule {
}
