/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.model.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class NaturalLangDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
  @Override
  public Object text(final IEObjectDescription ele) {
    return super.text(ele);
  }
}
