/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlxweb;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class NaturalLangWebModule /* implements AbstractNaturalLangWebModule  */{
}
