/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlxweb;

/**
 * Deploy this class into a servlet container to enable DSL-specific services.
 */
/* @WebServlet(, ) */@SuppressWarnings("all")
public class NaturalLangServlet /* implements XtextServlet  */{
  private /* DisposableRegistry */Object disposableRegistry;

  @Override
  public DisposableRegistry init() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type NaturalLangWebSetup"
      + "\nThe method or field DisposableRegistry is undefined"
      + "\nThe field NaturalLangServlet.disposableRegistry refers to the missing type DisposableRegistry"
      + "\ninit cannot be resolved"
      + "\ngetInstance cannot be resolved");
  }

  @Override
  public Object destroy() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\nThe field NaturalLangServlet.disposableRegistry refers to the missing type DisposableRegistry"
      + "\nThe field NaturalLangServlet.disposableRegistry refers to the missing type DisposableRegistry"
      + "\nThe field NaturalLangServlet.disposableRegistry refers to the missing type DisposableRegistry"
      + "\n!== cannot be resolved"
      + "\ndispose cannot be resolved"
      + "\ndestroy cannot be resolved");
  }
}
