/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlxweb;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class NaturalLangWebSetup /* implements NaturalLangStandaloneSetup  */{
  @Override
  public /* Injector */Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Guice is undefined"
      + "\nThe method or field Modules2 is undefined"
      + "\nNaturalLangRuntimeModule cannot be resolved."
      + "\nNaturalLangIdeModule cannot be resolved."
      + "\ncreateInjector cannot be resolved"
      + "\nmixin cannot be resolved");
  }
}
