/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang.impl;

import org.xixum.nlx.naturalLang.Chapter_Unit_HI;
import org.xixum.nlx.naturalLang.NaturalLangPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chapter Unit HI</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Chapter_Unit_HIImpl extends MinimalEObjectImpl.Container implements Chapter_Unit_HI
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Chapter_Unit_HIImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NaturalLangPackage.Literals.CHAPTER_UNIT_HI;
  }

} //Chapter_Unit_HIImpl
