/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang.impl;

import org.xixum.nlx.naturalLang.HashNumber;
import org.xixum.nlx.naturalLang.NaturalLangPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hash Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HashNumberImpl extends NoNElementImpl implements HashNumber
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HashNumberImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NaturalLangPackage.Literals.HASH_NUMBER;
  }

} //HashNumberImpl
