/**
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.naturalLang.impl;

import org.xixum.nlx.naturalLang.LineSentenceChain;
import org.xixum.nlx.naturalLang.NaturalLangPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Line Sentence Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LineSentenceChainImpl extends MinimalEObjectImpl.Container implements LineSentenceChain
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LineSentenceChainImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NaturalLangPackage.Literals.LINE_SENTENCE_CHAIN;
  }

} //LineSentenceChainImpl
