/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.web;

import com.google.inject.Injector;
import de.validas.spedit.NaturalLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class NaturalLangWebSetup extends NaturalLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from NaturalLangRuntimeModule to Module"
      + "\nType mismatch: cannot convert from NaturalLangIdeModule to Module"
      + "\nType mismatch: cannot convert from NaturalLangWebModule to Module");
  }
}
