/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.ui.labeling;

import javax.annotation.Generated;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
  @Override
  public Object text(final IEObjectDescription ele) {
    return super.text(ele);
  }
}
