/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.web;

import de.validas.spedit.web.AbstractNaturalLangWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class NaturalLangWebModule extends AbstractNaturalLangWebModule {
}
