/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.ui.contentassist;

import de.validas.spedit.ui.contentassist.AbstractNaturalLangProposalProvider;
import javax.annotation.Generated;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangProposalProvider extends AbstractNaturalLangProposalProvider {
}
