/**
 * generated by Xtext 2.16.0
 */
package de.validas.spedit.scoping;

import de.validas.spedit.scoping.AbstractNaturalLangScopeProvider;
import javax.annotation.Generated;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
@Generated("org.eclipse.xtend.core.compiler.XtendGenerator")
public class NaturalLangScopeProvider extends AbstractNaturalLangScopeProvider {
}
